### ISSUE TITLE
ESP32 Pin Diagram SPI

### ISSUE THREAD

**Issue by adriangoris** [mcauser/micropython-max7219#2]
Does anyone have the pin diagram for an ESP32?

I attempted to wire up a 4 unit max7219 board to the the SPI 1 and 2 ports on the ESP32.
According to expressif's documentation the ESP32 has 4 SPI ports:
https://github.com/loboris/Lua-RTOS-ESP32-lobo/wiki/ESP32-SPI-pins

I tried on SPI(2)
Max7219 - ESP32
-----------
DIN - D12
CS - D15
CLK - D14

**Comment by randmor** [comment]
You can Google pin-out diagrams for the various ESP-32 boards. Search Google Images for faster results. You should specify the manufacturer and model of your ESP32 board as pin-outs often vary from manufacturer to manufacturer.  I used:
DIN <===> GPIO-13 (SPI MOSI)
CS  <===> GPIO-15 (SPI CS)
CLK <===> GPIO-14 (SPI CLK)

GPIO-12 is usually used for SPI MISO, but since the display (a slave device) is not sending data back to the ESP32 (the master device), MISO is not needed. Maybe you were using GPIO-12 when you should have been using GPIO-13. 

On my ESP-32 board (an Ai-Thinker NodeMCU-32S), the pins are labeled "conveniently" on the bottom side of the board, and the GPIO pin numbers are abbreviated to "P" plus the pin number. So, GPIO-13 is labeled "P13", etc. I keep an extra NodeMCU-32S board handy just so I can quickly verify my wiring. It would have been nicer if the pins were labeled on the component side of the board, but there wasn't enough room without going to a larger board size. 

I hope this helps even if I'm 8 months late with a response. Maybe another user will find the info useful.

**Comment by adriangoris** [comment]
Thank you. :-)
